global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'recurser-monitor'
    
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]


remote_read:
  - url: http://host.docker.internal:3000/prometheus/read
remote_write:
  - url: http://host.docker.internal:3000/prometheus/write
